version: "3.8"
services:
  web:
    container_name: flask-app
    build: .
    stop_signal: SIGINT
    env_file: 
      - .env
    ports:
      - 5000:5000
    depends_on:
      #- test-db
      - dev-db

  dev-db:
    container_name: postgres-dev
    image: postgres:15.1
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DEV_DB}
        TZ: ${POSTGRES_TZ}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    
  #test-db:
  #  container_name: postgres-test
  #  image: postgres:15.1
  #  restart: always
  #  environment:
  #      POSTGRES_USER: ${POSTGRES_USER}
  #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #      POSTGRES_DB: ${POSTGRES_TEST_DB}
  #      TZ: ${POSTGRES_TZ}
  #  ports:
  #    - ${POSTGRES_TEST_PORT}:5432
  
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
#    ports:
#      - ${PGADMIN_PORT_HOST}:${PGADMIN_PORT}
    
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
#  pgadmin-data:
